name: OpenCode

on:
  issue_comment:
    types: [created]

jobs:
  run:
    if: contains(github.event.comment.body, '/oc-')
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    uses: l-etabli/devtools/.github/workflows/opencode-logic.yml@main
    with:
      comment: ${{ github.event.comment.body }}
    secrets:
      OPENCODE_API_KEY: ${{ secrets.OPENCODE_API_KEY }}
